### ISSUE TITLE
下载文件时，设置超时时间2s，2s接口没响应，没能触发errorHandler事件，取消下载cancelToken也不管用了

### ISSUE THREAD

**Issue by EricWong1994** [GuoBinyong/umi-request-progress#1]
沙盒我暂时没写，公司项目。

**Comment by EricWong1994** [comment]
请求配置如下
`{
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
    cancelToken: new CancelToken(function executor(c) {
      cancel = c;
    }),
    errorHandler: (error) => {
      console.log('error: ', error);
      if (error?.type === 'Timeout') {
        throw new Error('请求超时');
      }
      if (error?.request?.options?.cancelToken) {
        throw new Error('取消请求');
      }
      throw error;
    },
    // //下载进度事件的回调函数
    onResProgress:function( ev: ProgressEvent){
      console.log('响应ev: ', ev);
      console.log('响应时间: ', ev.timeStamp / 1000)
      if (ev?.timeStamp >= 15 * 1000) {
        console.log('超时 bbbbbbbbbbb')
        cancelDownload()
        
        throw new Error('请求超时');
      }
    },
    timeout: 5 * 1000,
}

export async function cancelDownload() {
  return cancel && cancel();
}`

**Comment by EricWong1994** [comment]
![image](https://user-images.githubusercontent.com/48429995/177308089-abe1968c-7fe9-4fc6-958d-44dabad5e8da.png)

**Comment by GuoBinyong** [comment]
原来没有支持这些参数，现在已支持，可更新到 v1.1.0

**Comment by EricWong1994** [comment]
强，谢谢大佬> 原来没有支持这些参数，现在已支持，可更新到 v1.1.0
